name: thoth-core pull request ci

on: [pull_request]

jobs:
  check-and-set-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for core changes
        run: git diff --quiet origin/main origin/${{ github.head_ref }} -- core
        id: thoth_core_diff
        shell: bash {0}
        continue-on-error: true
      - name: Check thoth-core labels
        if: steps.thoth_core_diff.outcome != 'success'
        uses: docker://agilepathway/pull-request-label-checker:latest
        id: thoth_core_exists
        with:
          none_of: thoth-core
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Label thoth-core draft prs
        if: steps.thoth_core_diff.outcome != 'success' && steps.thoth_core_exists.outcome == 'success'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: thoth-core-draft
      - name: Label thoth-core prs
        if: steps.thoth_core_diff.outcome != 'success' && steps.thoth_core_exists.outcome != 'success'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: thoth-core
