name: thoth-core pull request ci

on: [pull_request]

jobs:
  check-and-set-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Check for corechanges files
        run: echo ::set-output name=corechanges::$(if git diff --quiet origin/main..${{ steps.extract_branch.outputs.branch }}/core; then echo "true"; else echo "false"; fi)
      - name: Check thoth-core labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        id: thoth_core_exists
        with:
          one_of: thoth-core
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Label thoth-core draft prs
        if: steps.thoth_core_exists.outcome == 'success'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: thoth-core-draft
      - name: Label thoth-core prs
        if: steps.thoth_core_exists.outcome != 'success'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: thoth-core

